# define the cpu used by the HiFive1 board
export CPU = fe310
export CPU_MODEL = fe310

# Uses UART0 for stdio input/output (comment out to disable)
USEMODULE += uart_stdio


export FLASHER = $(RIOTBOARD)/$(BOARD)/dist/flasher.sh

